### ISSUE TITLE
Obtain the chromosome (start/end) position after running SalmonTE.py quant

### ISSUE THREAD

**Issue by ferygood** [LiuzLab/SalmonTE#42]
Hello,

Is there a way to know the chromosome position (e.g. chr1 145233 145561) where my reads map to after running `SalmonTE.py quant`?

Because after running `SalmonTE.py quant`, I can only view the TPM or count in the EXPR.csv. I want to know which start/end position do the TEs actually map to the reference.

Thank you for your help!

**Comment by hyunhwaj** [comment]
Hello @ferygood,

The goal of the SalmonTE is to quantify the overall abundance of each TE from a sample, and it doesn't report the position. The reason SalmonTE only quantifying the overall abundance is that RNA-seq has an instinct problem to locate the position because of the mapping ambiguity issue. 

Best,

Hyun-Hwan Jeong

**Comment by ferygood** [comment]
Hello Hyun-Hwan

Thank you for your detailed reply! SalmonTE is really a fast tool to quantify TEs from RNA-seq data and I appreciate your work.

Best,
Yao-Chung Chen
